markdown: rdiscount
permalink: /:title/
url: http://manuqiao.github.io
name: ManuQiao 的个人博客
author: ManuQiao
qq: 502809661
email: qiaorujia@163.com
duoshuo: qiaorujia@163.com
beian: 
cnzz: 1253390016
weibo: 1826263020
github: ManuQiao
pygments: true
safe: true
paginate: 20
about: "这里是 ManuQiao 的个人博客"
